apiVersion: v1
kind: ServiceAccount
metadata:
  name: zchengjoey-pipelines-controller
  namespace: zchengjoey-pipelines
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: zchengjoey-pipelines
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zchengjoey-pipelines-webhook
  namespace: zchengjoey-pipelines
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: zchengjoey-pipelines