apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zchengjoey-pipelines-controller
  namespace: zchengjoey-pipelines
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: zchengjoey-pipelines
subjects:
  - kind: ServiceAccount
    name: zchengjoey-pipelines-controller
    namespace: zchengjoey-pipelines
roleRef:
  kind: Role
  name: zchengjoey-pipelines-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zchengjoey-pipelines-webhook
  namespace: zchengjoey-pipelines
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: zchengjoey-pipelines
subjects:
  - kind: ServiceAccount
    name: zchengjoey-pipelines-webhook
    namespace: zchengjoey-pipelines
roleRef:
  kind: Role
  name: zchengjoey-pipelines-webhook
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zchengjoey-pipelines-controller-leaderelection
  namespace: zchengjoey-pipelines
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: zchengjoey-pipelines
subjects:
  - kind: ServiceAccount
    name: zchengjoey-pipelines-controller
    namespace: zchengjoey-pipelines
roleRef:
  kind: Role
  name: zchengjoey-pipelines-leader-election
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zchengjoey-pipelines-webhook-leaderelection
  namespace: zchengjoey-pipelines
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: zchengjoey-pipelines
subjects:
  - kind: ServiceAccount
    name: zchengjoey-pipelines-webhook
    namespace: zchengjoey-pipelines
roleRef:
  kind: Role
  name: zchengjoey-pipelines-leader-election
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zchengjoey-pipelines-info
  namespace: zchengjoey-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: zchengjoey-pipelines
subjects:
    # Giving all system:authenticated users the access of the
    # ConfigMap which contains version information.
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zchengjoey-pipelines-info