apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tasks.zchengjoey.dev
  labels:
    zchengjoey.dev/release: devel
    knative.dev/crd-install: "true"
spec:
  group: zchengjoey.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Spec holds the desired state of the Task from the client
              type: object
              properties:
                command:
                  description: 'Entrypoint array. Not executed within a shell. The image''s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container''s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell'
                  type: array
                  items:
                    type: string
                description:
                  description: Description is a user-facing description of the task that may be used to populate a UI.
                  type: string
                image:
                  description: 'Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images'
                  type: string
                name:
                  description: Name of the Step specified as a DNS_LABEL. Each Step in a Task must have a unique name.
                  type: string
  names:
    kind: Task
    plural: tasks
    singular: task
    categories:
      - all
      - knative
  scope: Namespaced
