apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelineruns.zchengjoey.dev
  labels:
    zchengjoey.dev/release: devel
    knative.dev/crd-install: "true"
spec:
  group: zchengjoey.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                pipelineRef:
                  type: object
                  properties:
                    name:
                      description: 'Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names'
                      type: string
                pipelineSpec:
                  type: object
                  properties:
                    description:
                      description: Description is a user-facing description of the pipeline that may be used to populate a UI.
                      type: string
                    tasks:
                      description: Tasks declares the graph of Tasks that execute when this Pipeline is run.
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            description: Name is the name of this task within the context of a Pipeline. Name is used as a coordinate with the `from` and `runAfter` fields to establish the execution order of tasks relative to one another.
                            type: string
                          runAfter:
                            description: RunAfter is the list of PipelineTask names that should be executed before this Task executes. (Used to force a specific ordering in graph execution.)
                            type: array
                            items:
                              type: string
                          taskRef:
                            description: TaskRef is a reference to a task definition.
                            type: object
                            properties:
                              name:
                                description: 'Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names'
                                type: string
                          taskSpec:
                            description: TaskSpec is a specification of a task
                            type: object
                            properties:
                              apiVersion:
                                type: string
                              args:
                                type: array
                                items:
                                  type: string
                              command:
                                description: 'Entrypoint array. Not executed within a shell. The image''s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container''s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell'
                                type: array
                                items:
                                  type: string
                              description:
                                description: Description is a user-facing description of the task that may be used to populate a UI.
                                type: string
                              image:
                                description: 'Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images'
                                type: string
                              kind:
                                type: string
                              metadata:
                                type: object
                                properties:
                                  annotations:
                                    type: object
                                    x-kubernetes-preserve-unknown-fields: true
                                  labels:
                                    type: object
                                    x-kubernetes-preserve-unknown-fields: true
                              name:
                                description: Name of the Step specified as a DNS_LABEL. Each Step in a Task must have a unique name.
                                type: string
                              spec:
                                description: Spec is a specification of a custom task
                                type: string
                status:
                  description: Used for cancelling a pipelinerun (and maybe more later on)
                  type: string
            status:
              type: object
              required:
                - pipelineSpec
              properties:
                annotations:
                  description: Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                childReferences:
                  description: list of TaskRun and Run names, PipelineTask names, and API versions/kinds for children of this PipelineRun.
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      name:
                        description: Name is the name of the TaskRun or Run this is referencing.
                        type: string
                      pipelineTaskName:
                        description: PipelineTaskName is the name of the PipelineTask this is referencing.
                        type: string
                completionTime:
                  description: CompletionTime is the time the PipelineRun completed.
                  type: string
                conditions:
                  description: Conditions the latest available observations of a resource's current state.
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant).
                        type: string
                      message:
                        description: A human readable message indicating details about the transition.
                        type: string
                      reason:
                        description: The reason for the condition's last transition.
                        type: string
                      severity:
                        description: Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error.
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type of condition.
                        type: string
                finallyStartTime:
                  description: FinallyStartTime is when all non-finally tasks have been completed and only finally tasks are being executed.
                  type: string
                observedGeneration:
                  description: ObservedGeneration is the 'Generation' of the Service that was last processed by the controller.
                  type: integer
                  format: int64
                pipelineSpec:
                  description: PipelineRunSpec contains the exact spec used to instantiate the run
                  type: object
                  properties:
                    description:
                      description: Description is a user-facing description of the pipeline that may be used to populate a UI.
                      type: string
                    tasks:
                      description: Tasks declares the graph of Tasks that execute when this Pipeline is run.
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            description: Name is the name of this task within the context of a Pipeline. Name is used as a coordinate with the `from` and `runAfter` fields to establish the execution order of tasks relative to one another.
                            type: string
                          runAfter:
                            description: RunAfter is the list of PipelineTask names that should be executed before this Task executes. (Used to force a specific ordering in graph execution.)
                            type: array
                            items:
                              type: string
                          taskRef:
                            description: TaskRef is a reference to a task definition.
                            type: object
                            properties:
                              name:
                                description: 'Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names'
                                type: string
                          taskSpec:
                            description: TaskSpec is a specification of a task
                            type: object
                            properties:
                              apiVersion:
                                type: string
                              args:
                                type: array
                                items:
                                  type: string
                              command:
                                description: 'Entrypoint array. Not executed within a shell. The image''s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container''s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell'
                                type: array
                                items:
                                  type: string
                              description:
                                description: Description is a user-facing description of the task that may be used to populate a UI.
                                type: string
                              image:
                                description: 'Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images'
                                type: string
                              kind:
                                type: string
                              metadata:
                                type: object
                                properties:
                                  annotations:
                                    type: object
                                    x-kubernetes-preserve-unknown-fields: true
                                  labels:
                                    type: object
                                    x-kubernetes-preserve-unknown-fields: true
                              name:
                                description: Name of the Step specified as a DNS_LABEL. Each Step in a Task must have a unique name.
                                type: string
                              spec:
                                description: Spec is a specification of a custom task
                                type: string
                startTime:
                  description: StartTime is the time the PipelineRun is actually started.
                  type: string
  names:
    kind: PipelineRun
    plural: pipelineruns
    singular: pipelinerun
    categories:
      - all
      - knative
  scope: Namespaced
