apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.zchengjoey.dev
  labels:
    zchengjoey.dev/release: devel
    knative.dev/crd-install: "true"
spec:
  group: zchengjoey.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Spec holds the desired state of the Pipeline from the client
              type: object
              properties:
                description:
                  description: Description is a user-facing description of the pipeline that may be used to populate a UI.
                  type: string
                tasks:
                  description: Tasks declares the graph of Tasks that execute when this Pipeline is run.
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        description: Name is the name of this task within the context of a Pipeline. Name is used as a coordinate with the `from` and `runAfter` fields to establish the execution order of tasks relative to one another.
                        type: string
                      runAfter:
                        description: RunAfter is the list of PipelineTask names that should be executed before this Task executes. (Used to force a specific ordering in graph execution.)
                        type: array
                        items:
                          type: string
                      taskRef:
                        description: TaskRef is a reference to a task definition.
                        type: object
                        properties:
                          name:
                            description: 'Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names'
                            type: string
                      taskSpec:
                        description: TaskSpec is a specification of a task
                        type: object
                        properties:
                          apiVersion:
                            type: string
                          args:
                            type: array
                            items:
                              type: string
                          command:
                            description: 'Entrypoint array. Not executed within a shell. The image''s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container''s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell'
                            type: array
                            items:
                              type: string
                          description:
                            description: Description is a user-facing description of the task that may be used to populate a UI.
                            type: string
                          image:
                            description: 'Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images'
                            type: string
                          kind:
                            type: string
                          metadata:
                            type: object
                            properties:
                              annotations:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                              labels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                          name:
                            description: Name of the Step specified as a DNS_LABEL. Each Step in a Task must have a unique name.
                            type: string
                          spec:
                            description: Spec is a specification of a custom task
                            type: string
  names:
    kind: Pipeline
    plural: pipelines
    singular: pipeline
    categories:
      - all
      - knative
  scope: Namespaced
