apiVersion: apps/v1
kind: Deployment
metadata:
  name: zchengjoey-pipelines-controller
  namespace: zchengjoey-pipelines
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: zchengjoey-pipelines
    # zchengjoey.dev/release value replaced with inputs.params.versionTag in pipeline/zchengjoey/publish.yaml
    pipeline.zchengjoey.dev/release: "devel"
    # labels below are related to istio and should not be used for resource lookup
    version: "devel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: controller
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: zchengjoey-pipelines
  template:
    metadata:
      labels:
        app.kubernetes.io/name: controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: "devel"
        app.kubernetes.io/part-of: zchengjoey-pipelines
        # zchengjoey.dev/release value replaced with inputs.params.versionTag in pipeline/zchengjoey/publish.yaml
        pipeline.zchengjoey.dev/release: "devel"
        # labels below are related to istio and should not be used for resource lookup
        app: zchengjoey-pipelines-controller
        version: "devel"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: NotIn
                  values:
                  - windows
      serviceAccountName: zchengjoey-pipelines-controller
      containers:
      - name: zchengjoey-pipelines-controller
        image: docker.io/zhengc/controller-389f9c76a2f597848ced98e9c26be870@sha256:2c74a424f2cba697d0e22b8282128e8699cb9e447e7244cb36e0ae979781c466
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METRICS_DOMAIN
          value: zchengjoey.dev/pipeline
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          # User 65532 is the distroless nonroot user ID
          runAsUser: 65532
          runAsGroup: 65532
        ports:
        - name: profiling
          containerPort: 8008
        - name: probes
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: probes
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: probes
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: zchengjoey-pipelines
    # zchengjoey.dev/release value replaced with inputs.params.versionTag in pipeline/zchengjoey/publish.yaml
    pipeline.zchengjoey.dev/release: "devel"
    # labels below are related to istio and should not be used for resource lookup
    app: zchengjoey-pipelines-controller
    version: "devel"
  name: zchengjoey-pipelines-controller
  namespace: zchengjoey-pipelines
spec:
  ports:
  - name: http-profiling
    port: 8008
    targetPort: 8008
  - name: probes
    port: 8080
  selector:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: zchengjoey-pipelines
